version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "trashtunes-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1refez5j05rh4"
s3_prefix = "trashtunes-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

